# action.yml
name: 'GitHub Action for Gatsby CLI'
description: 'This Action wraps the Gatsby CLI to enable common Gatsby commands.'
inputs:
  gatsby-arg:
    description: 'Arguments to pass to Gatsby CLI'
    required: true
    default: 'build'
  project-path:
    description: 'relative path in which execute the gatsby command'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gatsby-arg }}
    - ${{ inputs.project-path }}  
